#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    Reject,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ErrorCode {
    CanonicalControlByte,
    EmptySurface,
    InvalidHeader,
    InvalidEntrySyntax,
    DuplicateEntry,
    MissingPhase,
    MissingTask,
    InvalidPhase,
    InvalidTask,
    MissingRequiredPrinciple,
    MissingRequiredDuty,
    MissingRequiredBan,
    MissingRequiredEvidence,
    MissingRequiredOwnerRoot,
    ForbiddenToken,
    AmbientNetworkAllowed,
    ProbabilisticTruthAllowed,
    HiddenRandomnessAllowed,
    PlaceholderAllowed,
    FakeClosureClaim,
    UnsupportedGlobalClosure,
    MissingAuthorityLayer,
    InvalidAuthorityRank,
    DuplicateAuthorityRank,
    DuplicateAuthorityLayer,
    AuthorityOrderViolation,
    MissingAuthorityRule,
    AuthoritySupersessionViolation,
    OperatorOverrideConstitution,
    ArchiveAuthorityTooHigh,
    AmbientAuthority,
    MissingMasterAuthority,
    MissingIdentityRule,
    InvalidPhaseIdentity,
    InvalidTaskIdentity,
    InvalidWorkPackageIdentity,
    InvalidClosureIdentity,
    DuplicateIdentity,
    IdentityPrefixMismatch,
    MissingIdentityPhase,
    MissingIdentityTask,
    UnknownSupersessionTarget,
    SelfSupersession,
    UnscopedSupersession,
    MissingOwnerRoot,
    InvalidOwnerRoot,
    MissingEnforcementRule,
    MissingImplementationUnit,
    DuplicateImplementationUnit,
    InvalidImplementationUnit,
    UnderbuildViolation,
    MissingBehaviorProof,
    MissingTestProof,
    MissingFixtureProof,
    MissingReceiptProof,
    MisplacedOwnerRoot,
    DocsOnlyImplementation,
    EmptyImplementation,
    ThinPatchViolation,
    UnsupportedClosureStatus,
    UnsupportedEvidenceClaim,
    MissingDeliveryRule,
    MissingDeliveryArtifact,
    DuplicateDeliveryArtifact,
    InvalidDeliveryArtifact,
    MissingProofBinding,
    DuplicateProofBinding,
    InvalidProofBinding,
    ClosureBeforeReceipt,
    MissingCommandRecord,
    ReflectionBeforeArtifact,
    UnknownEvidencePath,
    MissingChallengeRule,
    MissingReviewGate,
    DuplicateReviewGate,
    InvalidReviewGate,
    MissingChallengeRight,
    DuplicateChallengeRight,
    InvalidChallengeRight,
    MissingRollbackAuthority,
    DuplicateRollbackAuthority,
    InvalidRollbackAuthority,
    MissingAmendmentGate,
    DuplicateAmendmentGate,
    InvalidAmendmentGate,
    RollbackWithoutReceipt,
    AmendmentAuthorityBypass,
    ArchivePrimaryAmendment,
    RetaliationAllowed,
    UnboundedAmendment,
    MissingControlRule,
    MissingControlSurface,
    DuplicateControlSurface,
    InvalidControlSurface,
    MissingControlField,
    DuplicateControlField,
    InvalidControlField,
    MissingPassTemplate,
    DuplicatePassTemplate,
    InvalidPassTemplate,
    ControlSurfaceDrift,
    MissingBlockerBinding,
    MissingTruthSnapshotBinding,
    MissingOwnerRootRule,
    MissingOwnerRootBinding,
    DuplicateOwnerRootBinding,
    InvalidOwnerRootBinding,
    MissingRootResponsibility,
    DuplicateRootResponsibility,
    InvalidRootResponsibility,
    RootOwnershipViolation,
    PlatformRootUnbounded,
    ProductRootCoreOwnership,
    MissingPublicInterestRule,
    MissingSafeguard,
    DuplicateSafeguard,
    InvalidSafeguard,
    MissingParticipationRight,
    DuplicateParticipationRight,
    InvalidParticipationRight,
    MissingAntiExtractiveDuty,
    DuplicateAntiExtractiveDuty,
    InvalidAntiExtractiveDuty,
    MissingStewardshipClaim,
    DuplicateStewardshipClaim,
    InvalidStewardshipClaim,
    CaptureRiskAllowed,
    LaborParticipationBypass,
    PublicBenefitUnbound,
    ExtractiveDefaultAllowed,
    MissingBenchmarkRule,
    MissingBenchmarkTarget,
    DuplicateBenchmarkTarget,
    InvalidBenchmarkTarget,
    BenchmarkTargetUnstable,
    MissingEvidenceBinding,
    DuplicateEvidenceBinding,
    InvalidEvidenceBinding,
    BenchmarkMissingReceipt,
    MissingDefinitionOfDone,
    DuplicateDefinitionOfDone,
    InvalidDefinitionOfDone,
    ClosureFormulaViolation,
    MissingCanonRule,
    MissingCanonSource,
    DuplicateCanonSource,
    InvalidCanonSource,
    MissingRoadmapBinding,
    DuplicateRoadmapBinding,
    InvalidRoadmapBinding,
    MissingCanonValidationClaim,
    DuplicateCanonValidationClaim,
    InvalidCanonValidationClaim,
    CanonDriftAccepted,
    RoadmapCanonMismatch,
    CanonSourceUnbound,
    ArchiveAuthorityOverride,
    AmbientCanonAuthority,
    MissingFormalSemanticRule,
    MissingSemanticDomain,
    DuplicateSemanticDomain,
    InvalidSemanticDomain,
    MissingSemanticRuleBinding,
    DuplicateSemanticRuleBinding,
    InvalidSemanticRuleBinding,
    MissingTransitionLaw,
    DuplicateTransitionLaw,
    InvalidTransitionLaw,
    MissingInvariantBinding,
    DuplicateInvariantBinding,
    InvalidInvariantBinding,
    MissingSemanticProof,
    DuplicateSemanticProof,
    InvalidSemanticProof,
    SemanticProofUnbound,
    SemanticDriftAccepted,
    MissingCanonicalModelRule,
    MissingCanonicalModel,
    DuplicateCanonicalModel,
    InvalidCanonicalModel,
    MissingSchemaBinding,
    DuplicateSchemaBinding,
    InvalidSchemaBinding,
    MissingFieldBinding,
    DuplicateFieldBinding,
    InvalidFieldBinding,
    MissingModelBinding,
    DuplicateModelBinding,
    InvalidModelBinding,
    CanonicalModelUnbound,
    CanonicalModelDriftAccepted,
    MissingAcceptanceRule,
    MissingAcceptanceGolden,
    DuplicateAcceptanceGolden,
    InvalidAcceptanceGolden,
    MissingChallengeFixture,
    DuplicateChallengeFixture,
    InvalidChallengeFixture,
    MissingAcceptanceProof,
    DuplicateAcceptanceProof,
    InvalidAcceptanceProof,
    AcceptanceProofUnbound,
    AmbientTimeAllowed,
    MissingEngineRule,
    MissingEngineUnit,
    DuplicateEngineUnit,
    InvalidEngineUnit,
    MissingTransitionBinding,
    DuplicateTransitionBinding,
    InvalidTransitionBinding,
    MissingEngineProof,
    DuplicateEngineProof,
    InvalidEngineProof,
    InvalidEngineSurface,
    EngineProofUnbound,
    EngineDriftAccepted,
    MissingFalsificationRule,
    MissingNegativeCase,
    DuplicateNegativeCase,
    InvalidNegativeCase,
    MissingFalsificationHarness,
    DuplicateFalsificationHarness,
    InvalidFalsificationHarness,
    MissingRejectionAssertion,
    DuplicateRejectionAssertion,
    InvalidRejectionAssertion,
    MissingFalsificationProof,
    DuplicateFalsificationProof,
    InvalidFalsificationProof,
    FalsificationProofUnbound,
    NegativeFixtureAccepted,
    MissingReplayRule,
    MissingReplayReceipt,
    DuplicateReplayReceipt,
    InvalidReplayReceipt,
    MissingReplayWitness,
    DuplicateReplayWitness,
    InvalidReplayWitness,
    MissingReceiptChainBinding,
    DuplicateReceiptChainBinding,
    InvalidReceiptChainBinding,
    MissingReplayProof,
    DuplicateReplayProof,
    InvalidReplayProof,
    ReplayProofUnbound,
    OrphanReceiptBinding,
    ReplayDriftAccepted,
    ReceiptHashMismatch,
    MissingInterfaceRule,
    MissingInterfaceCommand,
    DuplicateInterfaceCommand,
    InvalidInterfaceCommand,
    MissingInterfaceWorkflow,
    DuplicateInterfaceWorkflow,
    InvalidInterfaceWorkflow,
    MissingInterfaceExample,
    DuplicateInterfaceExample,
    InvalidInterfaceExample,
    MissingInterfaceProof,
    DuplicateInterfaceProof,
    InvalidInterfaceProof,
    InterfaceProofUnbound,
    ManualOnlyInterface,
    InterfaceNetworkDependency,
    InterfaceDriftAccepted,
    MissingPackagingRule,
    MissingPackageUnit,
    DuplicatePackageUnit,
    InvalidPackageUnit,
    MissingReleaseBundle,
    DuplicateReleaseBundle,
    InvalidReleaseBundle,
    MissingDistributionCheck,
    DuplicateDistributionCheck,
    InvalidDistributionCheck,
    MissingPackagingProof,
    DuplicatePackagingProof,
    InvalidPackagingProof,
    PackagingProofUnbound,
    PackagingNetworkDependency,
    PackagingDriftAccepted,
    MissingDeploymentRule,
    MissingDeploymentTarget,
    DuplicateDeploymentTarget,
    InvalidDeploymentTarget,
    MissingComplianceHook,
    DuplicateComplianceHook,
    InvalidComplianceHook,
    MissingReleaseEvidence,
    DuplicateReleaseEvidence,
    InvalidReleaseEvidence,
    MissingDeploymentProof,
    DuplicateDeploymentProof,
    InvalidDeploymentProof,
    DeploymentProofUnbound,
    DeploymentNetworkDependency,
    DeploymentDriftAccepted,
    MissingEcosystemRule,
    MissingEcosystemDoc,
    DuplicateEcosystemDoc,
    InvalidEcosystemDoc,
    MissingEcosystemExample,
    DuplicateEcosystemExample,
    InvalidEcosystemExample,
    MissingEcosystemProof,
    DuplicateEcosystemProof,
    InvalidEcosystemProof,
    EcosystemProofUnbound,
    EcosystemNetworkDependency,
    EcosystemDocsOnly,
    EcosystemDriftAccepted,
    MissingEconomicsRule,
    MissingEconomicsFrame,
    DuplicateEconomicsFrame,
    InvalidEconomicsFrame,
    MissingEconomicsOutput,
    DuplicateEconomicsOutput,
    InvalidEconomicsOutput,
    MissingEconomicsProof,
    DuplicateEconomicsProof,
    InvalidEconomicsProof,
    EconomicsProofUnbound,
    EconomicsNetworkDependency,
    EconomicsCaptureAllowed,
    EconomicsExtractiveDefault,
    EconomicsDriftAccepted,
    MissingRedTeamRule,
    MissingRedTeamScenario,
    DuplicateRedTeamScenario,
    InvalidRedTeamScenario,
    MissingRollbackPath,
    DuplicateRollbackPath,
    InvalidRollbackPath,
    MissingRedTeamProof,
    DuplicateRedTeamProof,
    InvalidRedTeamProof,
    RedTeamProofUnbound,
    RedTeamNetworkDependency,
    RedTeamRollbackUnreceipted,
    RedTeamChallengeBypass,
    RemoteTruthRewriteAllowed,
    RedTeamDriftAccepted,
    CorpusDriftAccepted,
    MissingClosureRule,
    MissingClosureTask,
    DuplicateClosureTask,
    InvalidClosureTask,
    MissingClosureOutputGate,
    DuplicateClosureOutputGate,
    InvalidClosureOutputGate,
    MissingClosureProof,
    DuplicateClosureProof,
    InvalidClosureProof,
    ClosureProofUnbound,
    ClosureNetworkDependency,
    ClosureDocsOnly,
    ClosureDriftAccepted,
    ClosureUnreceipted,
    ClosureOutputPremature,
}

impl ErrorCode {
    pub fn as_str(self) -> &'static str {
        match self {
            ErrorCode::CanonicalControlByte => "canonical_control_byte",
            ErrorCode::EmptySurface => "empty_surface",
            ErrorCode::InvalidHeader => "invalid_header",
            ErrorCode::InvalidEntrySyntax => "invalid_entry_syntax",
            ErrorCode::DuplicateEntry => "duplicate_entry",
            ErrorCode::MissingPhase => "missing_phase",
            ErrorCode::MissingTask => "missing_task",
            ErrorCode::InvalidPhase => "invalid_phase",
            ErrorCode::InvalidTask => "invalid_task",
            ErrorCode::MissingRequiredPrinciple => "missing_required_principle",
            ErrorCode::MissingRequiredDuty => "missing_required_duty",
            ErrorCode::MissingRequiredBan => "missing_required_ban",
            ErrorCode::MissingRequiredEvidence => "missing_required_evidence",
            ErrorCode::MissingRequiredOwnerRoot => "missing_required_owner_root",
            ErrorCode::ForbiddenToken => "forbidden_token",
            ErrorCode::AmbientNetworkAllowed => "ambient_network_allowed",
            ErrorCode::ProbabilisticTruthAllowed => "probabilistic_truth_allowed",
            ErrorCode::HiddenRandomnessAllowed => "hidden_randomness_allowed",
            ErrorCode::PlaceholderAllowed => "placeholder_allowed",
            ErrorCode::FakeClosureClaim => "fake_closure_claim",
            ErrorCode::UnsupportedGlobalClosure => "unsupported_global_closure",
            ErrorCode::MissingAuthorityLayer => "missing_authority_layer",
            ErrorCode::InvalidAuthorityRank => "invalid_authority_rank",
            ErrorCode::DuplicateAuthorityRank => "duplicate_authority_rank",
            ErrorCode::DuplicateAuthorityLayer => "duplicate_authority_layer",
            ErrorCode::AuthorityOrderViolation => "authority_order_violation",
            ErrorCode::MissingAuthorityRule => "missing_authority_rule",
            ErrorCode::AuthoritySupersessionViolation => "authority_supersession_violation",
            ErrorCode::OperatorOverrideConstitution => "operator_override_constitution",
            ErrorCode::ArchiveAuthorityTooHigh => "archive_authority_too_high",
            ErrorCode::AmbientAuthority => "ambient_authority",
            ErrorCode::MissingMasterAuthority => "missing_master_authority",
            ErrorCode::MissingIdentityRule => "missing_identity_rule",
            ErrorCode::InvalidPhaseIdentity => "invalid_phase_identity",
            ErrorCode::InvalidTaskIdentity => "invalid_task_identity",
            ErrorCode::InvalidWorkPackageIdentity => "invalid_work_package_identity",
            ErrorCode::InvalidClosureIdentity => "invalid_closure_identity",
            ErrorCode::DuplicateIdentity => "duplicate_identity",
            ErrorCode::IdentityPrefixMismatch => "identity_prefix_mismatch",
            ErrorCode::MissingIdentityPhase => "missing_identity_phase",
            ErrorCode::MissingIdentityTask => "missing_identity_task",
            ErrorCode::UnknownSupersessionTarget => "unknown_supersession_target",
            ErrorCode::SelfSupersession => "self_supersession",
            ErrorCode::UnscopedSupersession => "unscoped_supersession",
            ErrorCode::MissingOwnerRoot => "missing_owner_root",
            ErrorCode::InvalidOwnerRoot => "invalid_owner_root",
            ErrorCode::MissingEnforcementRule => "missing_enforcement_rule",
            ErrorCode::MissingImplementationUnit => "missing_implementation_unit",
            ErrorCode::DuplicateImplementationUnit => "duplicate_implementation_unit",
            ErrorCode::InvalidImplementationUnit => "invalid_implementation_unit",
            ErrorCode::UnderbuildViolation => "underbuild_violation",
            ErrorCode::MissingBehaviorProof => "missing_behavior_proof",
            ErrorCode::MissingTestProof => "missing_test_proof",
            ErrorCode::MissingFixtureProof => "missing_fixture_proof",
            ErrorCode::MissingReceiptProof => "missing_receipt_proof",
            ErrorCode::MisplacedOwnerRoot => "misplaced_owner_root",
            ErrorCode::DocsOnlyImplementation => "docs_only_implementation",
            ErrorCode::EmptyImplementation => "empty_implementation",
            ErrorCode::ThinPatchViolation => "thin_patch_violation",
            ErrorCode::UnsupportedClosureStatus => "unsupported_closure_status",
            ErrorCode::UnsupportedEvidenceClaim => "unsupported_evidence_claim",
            ErrorCode::MissingDeliveryRule => "missing_delivery_rule",
            ErrorCode::MissingDeliveryArtifact => "missing_delivery_artifact",
            ErrorCode::DuplicateDeliveryArtifact => "duplicate_delivery_artifact",
            ErrorCode::InvalidDeliveryArtifact => "invalid_delivery_artifact",
            ErrorCode::MissingProofBinding => "missing_proof_binding",
            ErrorCode::DuplicateProofBinding => "duplicate_proof_binding",
            ErrorCode::InvalidProofBinding => "invalid_proof_binding",
            ErrorCode::ClosureBeforeReceipt => "closure_before_receipt",
            ErrorCode::MissingCommandRecord => "missing_command_record",
            ErrorCode::ReflectionBeforeArtifact => "reflection_before_artifact",
            ErrorCode::UnknownEvidencePath => "unknown_evidence_path",
            ErrorCode::MissingChallengeRule => "missing_challenge_rule",
            ErrorCode::MissingReviewGate => "missing_review_gate",
            ErrorCode::DuplicateReviewGate => "duplicate_review_gate",
            ErrorCode::InvalidReviewGate => "invalid_review_gate",
            ErrorCode::MissingChallengeRight => "missing_challenge_right",
            ErrorCode::DuplicateChallengeRight => "duplicate_challenge_right",
            ErrorCode::InvalidChallengeRight => "invalid_challenge_right",
            ErrorCode::MissingRollbackAuthority => "missing_rollback_authority",
            ErrorCode::DuplicateRollbackAuthority => "duplicate_rollback_authority",
            ErrorCode::InvalidRollbackAuthority => "invalid_rollback_authority",
            ErrorCode::MissingAmendmentGate => "missing_amendment_gate",
            ErrorCode::DuplicateAmendmentGate => "duplicate_amendment_gate",
            ErrorCode::InvalidAmendmentGate => "invalid_amendment_gate",
            ErrorCode::RollbackWithoutReceipt => "rollback_without_receipt",
            ErrorCode::AmendmentAuthorityBypass => "amendment_authority_bypass",
            ErrorCode::ArchivePrimaryAmendment => "archive_primary_amendment",
            ErrorCode::RetaliationAllowed => "retaliation_allowed",
            ErrorCode::UnboundedAmendment => "unbounded_amendment",
            ErrorCode::MissingControlRule => "missing_control_rule",
            ErrorCode::MissingControlSurface => "missing_control_surface",
            ErrorCode::DuplicateControlSurface => "duplicate_control_surface",
            ErrorCode::InvalidControlSurface => "invalid_control_surface",
            ErrorCode::MissingControlField => "missing_control_field",
            ErrorCode::DuplicateControlField => "duplicate_control_field",
            ErrorCode::InvalidControlField => "invalid_control_field",
            ErrorCode::MissingPassTemplate => "missing_pass_template",
            ErrorCode::DuplicatePassTemplate => "duplicate_pass_template",
            ErrorCode::InvalidPassTemplate => "invalid_pass_template",
            ErrorCode::ControlSurfaceDrift => "control_surface_drift",
            ErrorCode::MissingBlockerBinding => "missing_blocker_binding",
            ErrorCode::MissingTruthSnapshotBinding => "missing_truth_snapshot_binding",
            ErrorCode::MissingOwnerRootRule => "missing_owner_root_rule",
            ErrorCode::MissingOwnerRootBinding => "missing_owner_root_binding",
            ErrorCode::DuplicateOwnerRootBinding => "duplicate_owner_root_binding",
            ErrorCode::InvalidOwnerRootBinding => "invalid_owner_root_binding",
            ErrorCode::MissingRootResponsibility => "missing_root_responsibility",
            ErrorCode::DuplicateRootResponsibility => "duplicate_root_responsibility",
            ErrorCode::InvalidRootResponsibility => "invalid_root_responsibility",
            ErrorCode::RootOwnershipViolation => "root_ownership_violation",
            ErrorCode::PlatformRootUnbounded => "platform_root_unbounded",
            ErrorCode::ProductRootCoreOwnership => "product_root_core_ownership",
            ErrorCode::MissingPublicInterestRule => "missing_public_interest_rule",
            ErrorCode::MissingSafeguard => "missing_safeguard",
            ErrorCode::DuplicateSafeguard => "duplicate_safeguard",
            ErrorCode::InvalidSafeguard => "invalid_safeguard",
            ErrorCode::MissingParticipationRight => "missing_participation_right",
            ErrorCode::DuplicateParticipationRight => "duplicate_participation_right",
            ErrorCode::InvalidParticipationRight => "invalid_participation_right",
            ErrorCode::MissingAntiExtractiveDuty => "missing_anti_extractive_duty",
            ErrorCode::DuplicateAntiExtractiveDuty => "duplicate_anti_extractive_duty",
            ErrorCode::InvalidAntiExtractiveDuty => "invalid_anti_extractive_duty",
            ErrorCode::MissingStewardshipClaim => "missing_stewardship_claim",
            ErrorCode::DuplicateStewardshipClaim => "duplicate_stewardship_claim",
            ErrorCode::InvalidStewardshipClaim => "invalid_stewardship_claim",
            ErrorCode::CaptureRiskAllowed => "capture_risk_allowed",
            ErrorCode::LaborParticipationBypass => "labor_participation_bypass",
            ErrorCode::PublicBenefitUnbound => "public_benefit_unbound",
            ErrorCode::ExtractiveDefaultAllowed => "extractive_default_allowed",
            ErrorCode::MissingBenchmarkRule => "missing_benchmark_rule",
            ErrorCode::MissingBenchmarkTarget => "missing_benchmark_target",
            ErrorCode::DuplicateBenchmarkTarget => "duplicate_benchmark_target",
            ErrorCode::InvalidBenchmarkTarget => "invalid_benchmark_target",
            ErrorCode::BenchmarkTargetUnstable => "benchmark_target_unstable",
            ErrorCode::MissingEvidenceBinding => "missing_evidence_binding",
            ErrorCode::DuplicateEvidenceBinding => "duplicate_evidence_binding",
            ErrorCode::InvalidEvidenceBinding => "invalid_evidence_binding",
            ErrorCode::BenchmarkMissingReceipt => "benchmark_missing_receipt",
            ErrorCode::MissingDefinitionOfDone => "missing_definition_of_done",
            ErrorCode::DuplicateDefinitionOfDone => "duplicate_definition_of_done",
            ErrorCode::InvalidDefinitionOfDone => "invalid_definition_of_done",
            ErrorCode::ClosureFormulaViolation => "closure_formula_violation",
            ErrorCode::MissingCanonRule => "missing_canon_rule",
            ErrorCode::MissingCanonSource => "missing_canon_source",
            ErrorCode::DuplicateCanonSource => "duplicate_canon_source",
            ErrorCode::InvalidCanonSource => "invalid_canon_source",
            ErrorCode::MissingRoadmapBinding => "missing_roadmap_binding",
            ErrorCode::DuplicateRoadmapBinding => "duplicate_roadmap_binding",
            ErrorCode::InvalidRoadmapBinding => "invalid_roadmap_binding",
            ErrorCode::MissingCanonValidationClaim => "missing_canon_validation_claim",
            ErrorCode::DuplicateCanonValidationClaim => "duplicate_canon_validation_claim",
            ErrorCode::InvalidCanonValidationClaim => "invalid_canon_validation_claim",
            ErrorCode::CanonDriftAccepted => "canon_drift_accepted",
            ErrorCode::RoadmapCanonMismatch => "roadmap_canon_mismatch",
            ErrorCode::CanonSourceUnbound => "canon_source_unbound",
            ErrorCode::ArchiveAuthorityOverride => "archive_authority_override",
            ErrorCode::AmbientCanonAuthority => "ambient_canon_authority",
            ErrorCode::MissingFormalSemanticRule => "missing_formal_semantic_rule",
            ErrorCode::MissingSemanticDomain => "missing_semantic_domain",
            ErrorCode::DuplicateSemanticDomain => "duplicate_semantic_domain",
            ErrorCode::InvalidSemanticDomain => "invalid_semantic_domain",
            ErrorCode::MissingSemanticRuleBinding => "missing_semantic_rule_binding",
            ErrorCode::DuplicateSemanticRuleBinding => "duplicate_semantic_rule_binding",
            ErrorCode::InvalidSemanticRuleBinding => "invalid_semantic_rule_binding",
            ErrorCode::MissingTransitionLaw => "missing_transition_law",
            ErrorCode::DuplicateTransitionLaw => "duplicate_transition_law",
            ErrorCode::InvalidTransitionLaw => "invalid_transition_law",
            ErrorCode::MissingInvariantBinding => "missing_invariant_binding",
            ErrorCode::DuplicateInvariantBinding => "duplicate_invariant_binding",
            ErrorCode::InvalidInvariantBinding => "invalid_invariant_binding",
            ErrorCode::MissingSemanticProof => "missing_semantic_proof",
            ErrorCode::DuplicateSemanticProof => "duplicate_semantic_proof",
            ErrorCode::InvalidSemanticProof => "invalid_semantic_proof",
            ErrorCode::SemanticProofUnbound => "semantic_proof_unbound",
            ErrorCode::SemanticDriftAccepted => "semantic_drift_accepted",
            ErrorCode::MissingCanonicalModelRule => "missing_canonical_model_rule",
            ErrorCode::MissingCanonicalModel => "missing_canonical_model",
            ErrorCode::DuplicateCanonicalModel => "duplicate_canonical_model",
            ErrorCode::InvalidCanonicalModel => "invalid_canonical_model",
            ErrorCode::MissingSchemaBinding => "missing_schema_binding",
            ErrorCode::DuplicateSchemaBinding => "duplicate_schema_binding",
            ErrorCode::InvalidSchemaBinding => "invalid_schema_binding",
            ErrorCode::MissingFieldBinding => "missing_field_binding",
            ErrorCode::DuplicateFieldBinding => "duplicate_field_binding",
            ErrorCode::InvalidFieldBinding => "invalid_field_binding",
            ErrorCode::MissingModelBinding => "missing_model_binding",
            ErrorCode::DuplicateModelBinding => "duplicate_model_binding",
            ErrorCode::InvalidModelBinding => "invalid_model_binding",
            ErrorCode::CanonicalModelUnbound => "canonical_model_unbound",
            ErrorCode::CanonicalModelDriftAccepted => "canonical_model_drift_accepted",
            ErrorCode::MissingAcceptanceRule => "missing_acceptance_rule",
            ErrorCode::MissingAcceptanceGolden => "missing_acceptance_golden",
            ErrorCode::DuplicateAcceptanceGolden => "duplicate_acceptance_golden",
            ErrorCode::InvalidAcceptanceGolden => "invalid_acceptance_golden",
            ErrorCode::MissingChallengeFixture => "missing_challenge_fixture",
            ErrorCode::DuplicateChallengeFixture => "duplicate_challenge_fixture",
            ErrorCode::InvalidChallengeFixture => "invalid_challenge_fixture",
            ErrorCode::MissingAcceptanceProof => "missing_acceptance_proof",
            ErrorCode::DuplicateAcceptanceProof => "duplicate_acceptance_proof",
            ErrorCode::InvalidAcceptanceProof => "invalid_acceptance_proof",
            ErrorCode::AcceptanceProofUnbound => "acceptance_proof_unbound",
            ErrorCode::AmbientTimeAllowed => "ambient_time_allowed",
            ErrorCode::MissingEngineRule => "missing_engine_rule",
            ErrorCode::MissingEngineUnit => "missing_engine_unit",
            ErrorCode::DuplicateEngineUnit => "duplicate_engine_unit",
            ErrorCode::InvalidEngineUnit => "invalid_engine_unit",
            ErrorCode::MissingTransitionBinding => "missing_transition_binding",
            ErrorCode::DuplicateTransitionBinding => "duplicate_transition_binding",
            ErrorCode::InvalidTransitionBinding => "invalid_transition_binding",
            ErrorCode::MissingEngineProof => "missing_engine_proof",
            ErrorCode::DuplicateEngineProof => "duplicate_engine_proof",
            ErrorCode::InvalidEngineProof => "invalid_engine_proof",
            ErrorCode::InvalidEngineSurface => "invalid_engine_surface",
            ErrorCode::EngineProofUnbound => "engine_proof_unbound",
            ErrorCode::EngineDriftAccepted => "engine_drift_accepted",
            ErrorCode::MissingFalsificationRule => "missing_falsification_rule",
            ErrorCode::MissingNegativeCase => "missing_negative_case",
            ErrorCode::DuplicateNegativeCase => "duplicate_negative_case",
            ErrorCode::InvalidNegativeCase => "invalid_negative_case",
            ErrorCode::MissingFalsificationHarness => "missing_falsification_harness",
            ErrorCode::DuplicateFalsificationHarness => "duplicate_falsification_harness",
            ErrorCode::InvalidFalsificationHarness => "invalid_falsification_harness",
            ErrorCode::MissingRejectionAssertion => "missing_rejection_assertion",
            ErrorCode::DuplicateRejectionAssertion => "duplicate_rejection_assertion",
            ErrorCode::InvalidRejectionAssertion => "invalid_rejection_assertion",
            ErrorCode::MissingFalsificationProof => "missing_falsification_proof",
            ErrorCode::DuplicateFalsificationProof => "duplicate_falsification_proof",
            ErrorCode::InvalidFalsificationProof => "invalid_falsification_proof",
            ErrorCode::FalsificationProofUnbound => "falsification_proof_unbound",
            ErrorCode::NegativeFixtureAccepted => "negative_fixture_accepted",
            ErrorCode::MissingReplayRule => "missing_replay_rule",
            ErrorCode::MissingReplayReceipt => "missing_replay_receipt",
            ErrorCode::DuplicateReplayReceipt => "duplicate_replay_receipt",
            ErrorCode::InvalidReplayReceipt => "invalid_replay_receipt",
            ErrorCode::MissingReplayWitness => "missing_replay_witness",
            ErrorCode::DuplicateReplayWitness => "duplicate_replay_witness",
            ErrorCode::InvalidReplayWitness => "invalid_replay_witness",
            ErrorCode::MissingReceiptChainBinding => "missing_receipt_chain_binding",
            ErrorCode::DuplicateReceiptChainBinding => "duplicate_receipt_chain_binding",
            ErrorCode::InvalidReceiptChainBinding => "invalid_receipt_chain_binding",
            ErrorCode::MissingReplayProof => "missing_replay_proof",
            ErrorCode::DuplicateReplayProof => "duplicate_replay_proof",
            ErrorCode::InvalidReplayProof => "invalid_replay_proof",
            ErrorCode::ReplayProofUnbound => "replay_proof_unbound",
            ErrorCode::OrphanReceiptBinding => "orphan_receipt_binding",
            ErrorCode::ReplayDriftAccepted => "replay_drift_accepted",
            ErrorCode::ReceiptHashMismatch => "receipt_hash_mismatch",
            ErrorCode::MissingInterfaceRule => "missing_interface_rule",
            ErrorCode::MissingInterfaceCommand => "missing_interface_command",
            ErrorCode::DuplicateInterfaceCommand => "duplicate_interface_command",
            ErrorCode::InvalidInterfaceCommand => "invalid_interface_command",
            ErrorCode::MissingInterfaceWorkflow => "missing_interface_workflow",
            ErrorCode::DuplicateInterfaceWorkflow => "duplicate_interface_workflow",
            ErrorCode::InvalidInterfaceWorkflow => "invalid_interface_workflow",
            ErrorCode::MissingInterfaceExample => "missing_interface_example",
            ErrorCode::DuplicateInterfaceExample => "duplicate_interface_example",
            ErrorCode::InvalidInterfaceExample => "invalid_interface_example",
            ErrorCode::MissingInterfaceProof => "missing_interface_proof",
            ErrorCode::DuplicateInterfaceProof => "duplicate_interface_proof",
            ErrorCode::InvalidInterfaceProof => "invalid_interface_proof",
            ErrorCode::InterfaceProofUnbound => "interface_proof_unbound",
            ErrorCode::ManualOnlyInterface => "manual_only_interface",
            ErrorCode::InterfaceNetworkDependency => "interface_network_dependency",
            ErrorCode::InterfaceDriftAccepted => "interface_drift_accepted",
            ErrorCode::MissingPackagingRule => "missing_packaging_rule",
            ErrorCode::MissingPackageUnit => "missing_package_unit",
            ErrorCode::DuplicatePackageUnit => "duplicate_package_unit",
            ErrorCode::InvalidPackageUnit => "invalid_package_unit",
            ErrorCode::MissingReleaseBundle => "missing_release_bundle",
            ErrorCode::DuplicateReleaseBundle => "duplicate_release_bundle",
            ErrorCode::InvalidReleaseBundle => "invalid_release_bundle",
            ErrorCode::MissingDistributionCheck => "missing_distribution_check",
            ErrorCode::DuplicateDistributionCheck => "duplicate_distribution_check",
            ErrorCode::InvalidDistributionCheck => "invalid_distribution_check",
            ErrorCode::MissingPackagingProof => "missing_packaging_proof",
            ErrorCode::DuplicatePackagingProof => "duplicate_packaging_proof",
            ErrorCode::InvalidPackagingProof => "invalid_packaging_proof",
            ErrorCode::PackagingProofUnbound => "packaging_proof_unbound",
            ErrorCode::PackagingNetworkDependency => "packaging_network_dependency",
            ErrorCode::PackagingDriftAccepted => "packaging_drift_accepted",
            ErrorCode::MissingDeploymentRule => "missing_deployment_rule",
            ErrorCode::MissingDeploymentTarget => "missing_deployment_target",
            ErrorCode::DuplicateDeploymentTarget => "duplicate_deployment_target",
            ErrorCode::InvalidDeploymentTarget => "invalid_deployment_target",
            ErrorCode::MissingComplianceHook => "missing_compliance_hook",
            ErrorCode::DuplicateComplianceHook => "duplicate_compliance_hook",
            ErrorCode::InvalidComplianceHook => "invalid_compliance_hook",
            ErrorCode::MissingReleaseEvidence => "missing_release_evidence",
            ErrorCode::DuplicateReleaseEvidence => "duplicate_release_evidence",
            ErrorCode::InvalidReleaseEvidence => "invalid_release_evidence",
            ErrorCode::MissingDeploymentProof => "missing_deployment_proof",
            ErrorCode::DuplicateDeploymentProof => "duplicate_deployment_proof",
            ErrorCode::InvalidDeploymentProof => "invalid_deployment_proof",
            ErrorCode::DeploymentProofUnbound => "deployment_proof_unbound",
            ErrorCode::DeploymentNetworkDependency => "deployment_network_dependency",
            ErrorCode::DeploymentDriftAccepted => "deployment_drift_accepted",
            ErrorCode::MissingEcosystemRule => "missing_ecosystem_rule",
            ErrorCode::MissingEcosystemDoc => "missing_ecosystem_doc",
            ErrorCode::DuplicateEcosystemDoc => "duplicate_ecosystem_doc",
            ErrorCode::InvalidEcosystemDoc => "invalid_ecosystem_doc",
            ErrorCode::MissingEcosystemExample => "missing_ecosystem_example",
            ErrorCode::DuplicateEcosystemExample => "duplicate_ecosystem_example",
            ErrorCode::InvalidEcosystemExample => "invalid_ecosystem_example",
            ErrorCode::MissingEcosystemProof => "missing_ecosystem_proof",
            ErrorCode::DuplicateEcosystemProof => "duplicate_ecosystem_proof",
            ErrorCode::InvalidEcosystemProof => "invalid_ecosystem_proof",
            ErrorCode::EcosystemProofUnbound => "ecosystem_proof_unbound",
            ErrorCode::EcosystemNetworkDependency => "ecosystem_network_dependency",
            ErrorCode::EcosystemDocsOnly => "ecosystem_docs_only",
            ErrorCode::EcosystemDriftAccepted => "ecosystem_drift_accepted",
            ErrorCode::MissingEconomicsRule => "missing_economics_rule",
            ErrorCode::MissingEconomicsFrame => "missing_economics_frame",
            ErrorCode::DuplicateEconomicsFrame => "duplicate_economics_frame",
            ErrorCode::InvalidEconomicsFrame => "invalid_economics_frame",
            ErrorCode::MissingEconomicsOutput => "missing_economics_output",
            ErrorCode::DuplicateEconomicsOutput => "duplicate_economics_output",
            ErrorCode::InvalidEconomicsOutput => "invalid_economics_output",
            ErrorCode::MissingEconomicsProof => "missing_economics_proof",
            ErrorCode::DuplicateEconomicsProof => "duplicate_economics_proof",
            ErrorCode::InvalidEconomicsProof => "invalid_economics_proof",
            ErrorCode::EconomicsProofUnbound => "economics_proof_unbound",
            ErrorCode::EconomicsNetworkDependency => "economics_network_dependency",
            ErrorCode::EconomicsCaptureAllowed => "economics_capture_allowed",
            ErrorCode::EconomicsExtractiveDefault => "economics_extractive_default",
            ErrorCode::EconomicsDriftAccepted => "economics_drift_accepted",
            ErrorCode::MissingRedTeamRule => "missing_redteam_rule",
            ErrorCode::MissingRedTeamScenario => "missing_redteam_scenario",
            ErrorCode::DuplicateRedTeamScenario => "duplicate_redteam_scenario",
            ErrorCode::InvalidRedTeamScenario => "invalid_redteam_scenario",
            ErrorCode::MissingRollbackPath => "missing_rollback_path",
            ErrorCode::DuplicateRollbackPath => "duplicate_rollback_path",
            ErrorCode::InvalidRollbackPath => "invalid_rollback_path",
            ErrorCode::MissingRedTeamProof => "missing_redteam_proof",
            ErrorCode::DuplicateRedTeamProof => "duplicate_redteam_proof",
            ErrorCode::InvalidRedTeamProof => "invalid_redteam_proof",
            ErrorCode::RedTeamProofUnbound => "redteam_proof_unbound",
            ErrorCode::RedTeamNetworkDependency => "redteam_network_dependency",
            ErrorCode::RedTeamRollbackUnreceipted => "redteam_rollback_unreceipted",
            ErrorCode::RedTeamChallengeBypass => "redteam_challenge_bypass",
            ErrorCode::RemoteTruthRewriteAllowed => "remote_truth_rewrite_allowed",
            ErrorCode::RedTeamDriftAccepted => "redteam_drift_accepted",
            ErrorCode::CorpusDriftAccepted => "corpus_drift_accepted",
            ErrorCode::MissingClosureRule => "missing_closure_rule",
            ErrorCode::MissingClosureTask => "missing_closure_task",
            ErrorCode::DuplicateClosureTask => "duplicate_closure_task",
            ErrorCode::InvalidClosureTask => "invalid_closure_task",
            ErrorCode::MissingClosureOutputGate => "missing_closure_output_gate",
            ErrorCode::DuplicateClosureOutputGate => "duplicate_closure_output_gate",
            ErrorCode::InvalidClosureOutputGate => "invalid_closure_output_gate",
            ErrorCode::MissingClosureProof => "missing_closure_proof",
            ErrorCode::DuplicateClosureProof => "duplicate_closure_proof",
            ErrorCode::InvalidClosureProof => "invalid_closure_proof",
            ErrorCode::ClosureProofUnbound => "closure_proof_unbound",
            ErrorCode::ClosureNetworkDependency => "closure_network_dependency",
            ErrorCode::ClosureDocsOnly => "closure_docs_only",
            ErrorCode::ClosureDriftAccepted => "closure_drift_accepted",
            ErrorCode::ClosureUnreceipted => "closure_unreceipted",
            ErrorCode::ClosureOutputPremature => "closure_output_premature",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidationError {
    pub code: ErrorCode,
    pub severity: Severity,
    pub location: String,
    pub detail: String,
}

impl ValidationError {
    pub fn reject(code: ErrorCode, location: impl Into<String>, detail: impl Into<String>) -> Self {
        Self {
            code,
            severity: Severity::Reject,
            location: location.into(),
            detail: detail.into(),
        }
    }

    pub fn canonical_line(&self) -> String {
        format!(
            "{}|{:?}|{}|{}",
            self.code.as_str(),
            self.severity,
            self.location,
            self.detail
        )
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Verdict {
    pub accepted: bool,
    pub errors: Vec<ValidationError>,
}

impl Verdict {
    pub fn accepted() -> Self {
        Self {
            accepted: true,
            errors: Vec::new(),
        }
    }

    pub fn rejected(mut errors: Vec<ValidationError>) -> Self {
        errors.sort_by(|left, right| {
            left.code
                .cmp(&right.code)
                .then(left.location.cmp(&right.location))
                .then(left.detail.cmp(&right.detail))
        });
        Self {
            accepted: false,
            errors,
        }
    }

    pub fn status_token(&self) -> &'static str {
        if self.accepted {
            "ACCEPTED"
        } else {
            "REJECTED"
        }
    }

    pub fn canonical_text(&self) -> String {
        let mut output = String::new();
        output.push_str("verdict=");
        output.push_str(self.status_token());
        output.push('\n');
        output.push_str(&format!("error_count={}\n", self.errors.len()));
        for (index, error) in self.errors.iter().enumerate() {
            output.push_str(&format!("error[{index:03}]={}\n", error.canonical_line()));
        }
        output
    }
}
